# Generated by Django 6.0.3 on 2026-03-28 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(verbose_name='تاريخ الزيارة')),
                ('month_label', models.CharField(blank=True, max_length=100, null=True, verbose_name='الشهر الهجري')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات الفني')),
                ('technician_approved', models.BooleanField(default=False, verbose_name='اعتماد الفني')),
                ('client_approved', models.BooleanField(default=False, verbose_name='اعتماد العميل')),
                ('technician_approved_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت اعتماد الفني')),
                ('client_approved_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت اعتماد العميل')),
                ('technician_signature', models.TextField(blank=True, null=True, verbose_name='توقيع الفني الإلكتروني')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='contracts.maintenancecontract', verbose_name='العقد')),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_visits', to=settings.AUTH_USER_MODEL, verbose_name='الفني')),
            ],
            options={
                'verbose_name': 'زيارة',
                'verbose_name_plural': 'الزيارات',
                'ordering': ['-visit_date', '-id'],
            },
        ),
    ]
