# Generated by Django 6.0.3 on 2026-03-28 19:17

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(choices=[('executive', 'مدير تنفيذي'), ('admin_assistant', 'مساعد إداري'), ('technician', 'فني'), ('client', 'عميل')], default='client', max_length=30, verbose_name='نوع المستخدم')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الجوال')),
                ('national_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الهوية / السجل')),
                ('must_change_password', models.BooleanField(default=False, verbose_name='يجب تغيير كلمة المرور')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'مستخدم',
                'verbose_name_plural': 'المستخدمون',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم المؤسسة')),
                ('unified_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='الرقم الموحد')),
                ('executive_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم المدير التنفيذي')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='institution/logos/', verbose_name='الشعار')),
                ('letterhead', models.ImageField(blank=True, null=True, upload_to='institution/letterheads/', verbose_name='مطبوعات المؤسسة')),
                ('stamp', models.ImageField(blank=True, null=True, upload_to='institution/stamps/', verbose_name='الختم')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='institution/signatures/', verbose_name='التوقيع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('users', models.ManyToManyField(blank=True, related_name='institutions', to=settings.AUTH_USER_MODEL, verbose_name='المستخدمون')),
            ],
            options={
                'verbose_name': 'مؤسسة',
                'verbose_name_plural': 'المؤسسات',
            },
        ),
    ]
