# Generated by Django 6.0.3 on 2026-03-28 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContractClauseTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان البند')),
                ('content', models.TextField(verbose_name='نص البند')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'قالب بند عقد',
                'verbose_name_plural': 'قوالب بنود العقود',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=100, unique=True, verbose_name='رقم العقد')),
                ('second_party_name', models.CharField(max_length=255, verbose_name='اسم الطرف الثاني')),
                ('building_name', models.CharField(max_length=255, verbose_name='اسم المبنى')),
                ('activity', models.CharField(blank=True, max_length=255, null=True, verbose_name='النشاط')),
                ('building_location', models.TextField(blank=True, null=True, verbose_name='موقع المبنى')),
                ('client_identifier', models.CharField(blank=True, max_length=100, null=True, verbose_name='معرف العميل')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(verbose_name='تاريخ النهاية')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'عقد صيانة',
                'verbose_name_plural': 'عقود الصيانة',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceContractClause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان البند')),
                ('content', models.TextField(verbose_name='نص البند')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'بند عقد',
                'verbose_name_plural': 'بنود العقود',
                'ordering': ['order', 'id'],
            },
        ),
    ]
