# Generated by Django 6.0.3 on 2026-03-28 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contractclausetemplate',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_clause_templates', to='core.institution', verbose_name='المؤسسة'),
        ),
        migrations.AddField(
            model_name='maintenancecontract',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_contracts', to=settings.AUTH_USER_MODEL, verbose_name='العميل'),
        ),
        migrations.AddField(
            model_name='maintenancecontract',
            name='executive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executive_contracts', to=settings.AUTH_USER_MODEL, verbose_name='المدير التنفيذي'),
        ),
        migrations.AddField(
            model_name='maintenancecontract',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='core.institution', verbose_name='المؤسسة'),
        ),
        migrations.AddField(
            model_name='maintenancecontractclause',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clauses', to='contracts.maintenancecontract', verbose_name='العقد'),
        ),
    ]
