# Generated by Django 6.0.3 on 2026-03-28 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateClauseTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clause_type', models.CharField(choices=[('safety_tools', 'وسائل السلامة المتوفرة'), ('fire_system', 'نظام الإطفاء')], max_length=30, verbose_name='نوع البند')),
                ('title', models.CharField(max_length=255, verbose_name='اسم البند')),
                ('details', models.CharField(blank=True, max_length=255, null=True, verbose_name='تفاصيل إضافية')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'قالب بند شهادة',
                'verbose_name_plural': 'قوالب بنود الشهادات',
                'ordering': ['clause_type', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CompletionCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(max_length=100, unique=True, verbose_name='رقم الشهادة')),
                ('work_type', models.CharField(choices=[('installation', 'تركيب'), ('maintenance', 'صيانة')], default='maintenance', max_length=30, verbose_name='نوع العمل')),
                ('beneficiary_name', models.CharField(max_length=255, verbose_name='اسم المستفيد')),
                ('owner_name', models.CharField(max_length=255, verbose_name='اسم المالك')),
                ('building_name', models.CharField(max_length=255, verbose_name='اسم المبنى')),
                ('activity', models.CharField(blank=True, max_length=255, null=True, verbose_name='النشاط')),
                ('building_location', models.TextField(blank=True, null=True, verbose_name='موقع المبنى')),
                ('issue_date', models.DateField(verbose_name='تاريخ الإصدار')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'شهادة إنهاء أعمال',
                'verbose_name_plural': 'شهادات إنهاء الأعمال',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CompletionCertificateClause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clause_type', models.CharField(choices=[('safety_tools', 'وسائل السلامة المتوفرة'), ('fire_system', 'نظام الإطفاء')], max_length=30, verbose_name='نوع البند')),
                ('work_type', models.CharField(choices=[('installation', 'تركيب'), ('maintenance', 'صيانة')], max_length=30, verbose_name='نوع العمل')),
                ('title', models.CharField(max_length=255, verbose_name='اسم البند')),
                ('details', models.CharField(blank=True, max_length=255, null=True, verbose_name='تفاصيل إضافية')),
                ('contract_expiry_date', models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء العقد')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'بند شهادة',
                'verbose_name_plural': 'بنود الشهادة',
                'ordering': ['clause_type', 'order', 'id'],
            },
        ),
    ]
