# Generated by Django 6.0.3 on 2026-03-28 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('certificates', '0001_initial'),
        ('contracts', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='certificateclausetemplate',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_clause_templates', to='core.institution', verbose_name='المؤسسة'),
        ),
        migrations.AddField(
            model_name='completioncertificate',
            name='client',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'client'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completion_certificates', to=settings.AUTH_USER_MODEL, verbose_name='العميل'),
        ),
        migrations.AddField(
            model_name='completioncertificate',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='completion_certificates', to='contracts.maintenancecontract', verbose_name='العقد'),
        ),
        migrations.AddField(
            model_name='completioncertificate',
            name='executive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executive_certificates', to=settings.AUTH_USER_MODEL, verbose_name='المدير التنفيذي'),
        ),
        migrations.AddField(
            model_name='completioncertificate',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='core.institution', verbose_name='المؤسسة'),
        ),
        migrations.AddField(
            model_name='completioncertificateclause',
            name='certificate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clauses', to='certificates.completioncertificate', verbose_name='الشهادة'),
        ),
    ]
