# Generated by Django 6.0.3 on 2026-03-29 07:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceQuotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_number', models.CharField(max_length=100, verbose_name='رقم عرض السعر')),
                ('client_display_name', models.CharField(max_length=255, verbose_name='اسم مؤسسة العميل')),
                ('building_name', models.CharField(max_length=255, verbose_name='اسم المبنى')),
                ('building_location', models.TextField(verbose_name='موقع المبنى')),
                ('issue_date', models.DateField(auto_now_add=True, verbose_name='تاريخ الإصدار')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('sent', 'مرسل'), ('accepted', 'مقبول'), ('rejected', 'مرفوض')], default='draft', max_length=20, verbose_name='الحالة')),
                ('payment_method', models.CharField(blank=True, choices=[('platform_card', 'بطاقة عبر المنصة'), ('bank_transfer', 'تحويل بنكي'), ('cash', 'نقداً')], max_length=30, null=True, verbose_name='طريقة الدفع')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='المجموع')),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الضريبة')),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الإجمالي')),
                ('grand_total_words', models.TextField(blank=True, null=True, verbose_name='المبلغ كتابة')),
                ('payment_terms', models.TextField(verbose_name='طريقة الدفع (الدفعات)')),
                ('execution_period', models.CharField(max_length=255, verbose_name='مدة التنفيذ')),
                ('institution_account_number', models.CharField(max_length=255, verbose_name='رقم حساب المؤسسة')),
                ('client_decision_note', models.TextField(blank=True, null=True, verbose_name='ملاحظة العميل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_quotations', to=settings.AUTH_USER_MODEL, verbose_name='العميل')),
                ('executive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executive_quotations', to=settings.AUTH_USER_MODEL, verbose_name='المدير التنفيذي')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='core.institution', verbose_name='المؤسسة')),
            ],
            options={
                'verbose_name': 'عرض سعر',
                'verbose_name_plural': 'عروض الأسعار',
            },
        ),
        migrations.CreateModel(
            name='PriceQuotationInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='اسم الدفعة')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='النسبة %')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='المبلغ')),
                ('due_description', models.CharField(max_length=255, verbose_name='موعد الدفع')),
                ('is_paid', models.BooleanField(default=False)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='quotations.pricequotation', verbose_name='عرض السعر')),
            ],
        ),
        migrations.CreateModel(
            name='PriceQuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='الإيضاحات')),
                ('quantity', models.PositiveIntegerField(verbose_name='الكمية')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر الفرادي')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='السعر الإجمالي')),
                ('order', models.PositiveIntegerField(default=0)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quotations.pricequotation', verbose_name='عرض السعر')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
