# Generated by Django 6.0.3 on 2026-03-29 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricequotation',
            name='execution_days',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد أيام التنفيذ'),
        ),
        migrations.AlterField(
            model_name='pricequotation',
            name='execution_period',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='مدة التنفيذ'),
        ),
    ]
